
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  analytics,
  team,
}: {
  children: React.ReactNode
  analytics: React.ReactNode,
  team: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col gap-4`}>
      {children}{analytics}{team}
      </body>
    </html>
  )
}
